[package]
name = "prismcast-media-gst"
description = "Linux GStreamer media platform implementation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
gstreamer.workspace = true
thiserror.workspace = true
tracing.workspace = true
prismcast-core = { path = "../prismcast-core" }
prismcast-media = { path = "../prismcast-media" }
serde.workspace = true
serde_json.workspace = true
prismcast-compositor = { path = "../prismcast-compositor", version = "0.1.0" }
