//! Authentication configuration for remote servers (IPC-001; PLAN.md §24).
//!
//! The Unix socket's primary access control is **filesystem permissions**
//! (ADR-0006 §5: the socket lives in `$XDG_RUNTIME_DIR/prismcast/` with
//! `0700`/`0600` modes, so only the owning user can connect). The default
//! local configuration therefore grants every session full
//! [`Permission::Admin`] rights without a handshake credential — this is the
//! documented "allow-local" policy.
//!
//! A bearer token or a password (SHA-256 challenge-response, protocol doc
//! §4) can additionally be required, either injected by the embedder
//! ([`AuthConfig::token`], [`AuthConfig::password`]) or read from
//! `$XDG_CONFIG_HOME/prismcast/remote.toml`:
//!
//! ```toml
//! token = "shared-secret"
//! # or: password = "shared-secret"   (mutually exclusive with `token`)
//! permissions = ["read", "control_scenes"]
//! ```
//!
//! The file is parsed with a small built-in parser covering exactly the keys
//! above (comments, sections, quoted strings, and string arrays); it is
//! an interim solution until the workspace adopts a TOML crate. When the
//! file is absent the allow-local policy applies; when it is malformed the
//! server falls back to allow-local with a warning (the socket's filesystem
//! permissions still gate access).

use std::path::{Path, PathBuf};

use base64::engine::general_purpose::STANDARD as BASE64;
use base64::Engine;
use rand::RngCore;
use sha2::{Digest, Sha256};

use prismcast_protocol::handshake::{AuthChallenge, AuthResponse, Permission};

/// How a server authenticates incoming sessions and which permissions it
/// grants them.
#[derive(Clone, PartialEq, Eq)]
pub enum AuthConfig {
    /// Local-trust policy: no credential required; every session receives the
    /// configured permissions (full `Admin` by default). Appropriate for the
    /// Unix socket, where filesystem permissions already restrict access to
    /// the owning user (ADR-0006 §5).
    AllowLocal {
        /// Permissions granted to every session.
        permissions: Vec<Permission>,
    },
    /// Bearer token required in `Identify` (`AuthResponse::Token`); sessions
    /// presenting the correct token receive the configured permissions.
    Token {
        /// The expected token.
        token: String,
        /// Permissions granted on success.
        permissions: Vec<Permission>,
    },
    /// Password verified by SHA-256 challenge-response (protocol doc §4):
    /// `Hello` advertises the salt and a per-session challenge; the client
    /// answers with `AuthResponse::Challenge`.
    Password {
        /// The configured password (never serialized or logged).
        password: String,
        /// Per-server-start salt, generated by [`AuthConfig::password`] or
        /// the `remote.toml` loader.
        salt: [u8; 32],
        /// Permissions granted on success.
        permissions: Vec<Permission>,
    },
}

impl AuthConfig {
    /// The default local policy: no credential, full [`Permission::Admin`].
    pub fn allow_local() -> Self {
        Self::AllowLocal {
            permissions: vec![Permission::Admin],
        }
    }

    /// Requires `token` and grants `permissions` on success.
    pub fn token(token: impl Into<String>, permissions: Vec<Permission>) -> Self {
        Self::Token {
            token: token.into(),
            permissions,
        }
    }

    /// Password auth (SHA-256 challenge-response, protocol doc §4): each
    /// session is offered a fresh challenge in `Hello`; the salt is generated
    /// here and stays stable for the configuration's (server's) lifetime.
    pub fn password(password: impl Into<String>, permissions: Vec<Permission>) -> Self {
        let mut salt = [0u8; 32];
        rand::rng().fill_bytes(&mut salt);
        Self::Password {
            password: password.into(),
            salt,
            permissions,
        }
    }

    /// A fresh per-session challenge when password auth is configured; `None`
    /// otherwise (token and allow-local policies advertise nothing in
    /// `Hello`). The salt is fixed per configuration; the challenge is
    /// generated per call and lives only in the handshake's stack frame —
    /// per-session, single-use, never stored in shared state.
    pub fn challenge_for_session(&self) -> Option<AuthChallenge> {
        match self {
            Self::Password { salt, .. } => {
                let mut challenge = [0u8; 32];
                rand::rng().fill_bytes(&mut challenge);
                Some(AuthChallenge {
                    salt: BASE64.encode(salt),
                    challenge: BASE64.encode(challenge),
                })
            }
            Self::AllowLocal { .. } | Self::Token { .. } => None,
        }
    }

    /// Loads the configuration from an explicit `remote.toml` path.
    pub fn from_file(path: &Path) -> Result<Self, AuthError> {
        let content = std::fs::read_to_string(path).map_err(AuthError::Io)?;
        parse_remote_toml(&content)
    }

    /// Loads [`default_config_path`] if it exists; otherwise (or on a parse
    /// failure, with a warning logged) returns [`AuthConfig::allow_local`].
    pub fn load_default() -> Self {
        let path = default_config_path();
        if !path.is_file() {
            return Self::allow_local();
        }
        match Self::from_file(&path) {
            Ok(config) => config,
            Err(error) => {
                tracing::warn!(path = %path.display(), %error, "ignoring malformed remote.toml");
                Self::allow_local()
            }
        }
    }

    /// The permissions a successfully authenticated session receives.
    pub fn granted_permissions(&self) -> &[Permission] {
        match self {
            Self::AllowLocal { permissions }
            | Self::Token { permissions, .. }
            | Self::Password { permissions, .. } => permissions,
        }
    }

    /// Verifies the `Identify` authentication field, returning the granted
    /// permissions or `None` when authentication fails. `challenge` is the
    /// per-session challenge this session was offered in `Hello`
    /// ([`AuthConfig::challenge_for_session`]); it is required to verify a
    /// password answer, which binds the response to this session's salt and
    /// challenge.
    ///
    /// The response comparison is a plain string equality, not constant-time:
    /// acceptable here because the credential protects localhost-scope
    /// transports (Unix socket, loopback `ws://`), where timing oracles are
    /// not the threat model (protocol doc §4; TLS + token is the network
    /// path). Revisit if a non-loopback plaintext listener is ever added.
    pub(crate) fn authenticate(
        &self,
        auth: Option<&AuthResponse>,
        challenge: Option<&AuthChallenge>,
    ) -> Option<Vec<Permission>> {
        match self {
            Self::AllowLocal { permissions } => Some(permissions.clone()),
            Self::Token { token, permissions } => match auth {
                Some(AuthResponse::Token { token: presented }) if presented == token => {
                    Some(permissions.clone())
                }
                // Challenge-response is not offered by this server (no
                // challenge in `Hello`), so a challenge answer is a failure.
                _ => None,
            },
            Self::Password {
                password,
                permissions,
                ..
            } => match (auth, challenge) {
                (Some(AuthResponse::Challenge { response }), Some(issued)) => {
                    (response == &challenge_response(password, issued)).then(|| permissions.clone())
                }
                // Token answers and unissued challenges never authenticate
                // against a password policy.
                _ => None,
            },
        }
    }
}

impl std::fmt::Debug for AuthConfig {
    /// Redacts the credentials: neither token nor password may leak into
    /// logs.
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::AllowLocal { permissions } => f
                .debug_struct("AllowLocal")
                .field("permissions", permissions)
                .finish(),
            Self::Token { permissions, .. } => f
                .debug_struct("Token")
                .field("token", &"<redacted>")
                .field("permissions", permissions)
                .finish(),
            Self::Password {
                salt, permissions, ..
            } => f
                .debug_struct("Password")
                .field("password", &"<redacted>")
                .field("salt", &BASE64.encode(salt))
                .field("permissions", permissions)
                .finish(),
        }
    }
}

/// The obs-websocket challenge response (protocol doc §4):
/// `base64(sha256(base64(sha256(password + salt)) + challenge))`, where both
/// concatenations use the base64 *strings* carried by the [`AuthChallenge`].
/// This is the single implementation of the construction, shared by server
/// verification and both clients.
pub fn challenge_response(password: &str, challenge: &AuthChallenge) -> String {
    let secret = sha256_base64(&format!("{password}{}", challenge.salt));
    sha256_base64(&format!("{secret}{}", challenge.challenge))
}

fn sha256_base64(input: &str) -> String {
    BASE64.encode(Sha256::digest(input.as_bytes()))
}

/// The default auth configuration file:
/// `$XDG_CONFIG_HOME/prismcast/remote.toml` (falling back to
/// `~/.config/prismcast/remote.toml` when `XDG_CONFIG_HOME` is unset).
pub fn default_config_path() -> PathBuf {
    let base = std::env::var_os("XDG_CONFIG_HOME")
        .filter(|v| !v.is_empty())
        .map(PathBuf::from)
        .or_else(|| std::env::var_os("HOME").map(|home| PathBuf::from(home).join(".config")));
    match base {
        Some(base) => base.join("prismcast").join("remote.toml"),
        None => PathBuf::from("remote.toml"),
    }
}

/// Failures loading or parsing the auth configuration.
#[derive(Debug, thiserror::Error)]
pub enum AuthError {
    /// The file could not be read.
    #[error("I/O error: {0}")]
    Io(std::io::Error),
    /// A line in the file is not a recognized `key = value` pair.
    #[error("parse error on line {line}: {message}")]
    Parse {
        /// 1-based line number.
        line: usize,
        /// What went wrong.
        message: String,
    },
    /// A permission name in `permissions` is not a known scope.
    #[error("unknown permission: {0}")]
    UnknownPermission(String),
}

/// Parses the interim `remote.toml` subset (see module docs).
fn parse_remote_toml(content: &str) -> Result<AuthConfig, AuthError> {
    let mut token: Option<(String, usize)> = None;
    let mut password: Option<(String, usize)> = None;
    let mut permissions: Option<Vec<Permission>> = None;
    for (index, raw_line) in content.lines().enumerate() {
        let line = strip_comment(raw_line).trim().to_string();
        if line.is_empty() || (line.starts_with('[') && line.ends_with(']')) {
            continue;
        }
        let Some((key, value)) = line.split_once('=') else {
            return Err(AuthError::Parse {
                line: index + 1,
                message: "expected `key = value`".to_string(),
            });
        };
        let key = key.trim();
        let value = value.trim();
        match key {
            "token" => token = Some((parse_string(value, index + 1)?, index + 1)),
            "password" => password = Some((parse_string(value, index + 1)?, index + 1)),
            "permissions" => {
                let names = parse_string_array(value, index + 1)?;
                let mut parsed = Vec::with_capacity(names.len());
                for name in names {
                    let permission =
                        serde_json::from_value::<Permission>(serde_json::Value::String(name))
                            .map_err(|e| AuthError::UnknownPermission(e.to_string()))?;
                    parsed.push(permission);
                }
                permissions = Some(parsed);
            }
            other => {
                return Err(AuthError::Parse {
                    line: index + 1,
                    message: format!("unknown key `{other}`"),
                });
            }
        }
    }
    let permissions = permissions.unwrap_or_else(|| vec![Permission::Admin]);
    match (token, password) {
        (Some((_, token_line)), Some((_, password_line))) => Err(AuthError::Parse {
            line: token_line.max(password_line),
            message: "`token` and `password` are mutually exclusive".to_string(),
        }),
        (Some((token, _)), None) => Ok(AuthConfig::Token { token, permissions }),
        (None, Some((password, _))) => Ok(AuthConfig::password(password, permissions)),
        (None, None) => Ok(AuthConfig::AllowLocal { permissions }),
    }
}

/// Removes a `#` comment, honoring double-quoted strings.
fn strip_comment(line: &str) -> &str {
    let mut in_string = false;
    let mut escaped = false;
    for (index, ch) in line.char_indices() {
        match ch {
            '\\' if in_string => escaped = !escaped,
            '"' if !escaped => in_string = !in_string,
            '#' if !in_string => return &line[..index],
            _ => escaped = false,
        }
    }
    line
}

fn parse_string(value: &str, line: usize) -> Result<String, AuthError> {
    let inner = value
        .strip_prefix('"')
        .and_then(|v| v.strip_suffix('"'))
        .ok_or_else(|| AuthError::Parse {
            line,
            message: "expected a quoted string".to_string(),
        })?;
    Ok(inner.replace("\\\"", "\"").replace("\\\\", "\\"))
}

fn parse_string_array(value: &str, line: usize) -> Result<Vec<String>, AuthError> {
    let inner = value
        .strip_prefix('[')
        .and_then(|v| v.strip_suffix(']'))
        .ok_or_else(|| AuthError::Parse {
            line,
            message: "expected an array of quoted strings".to_string(),
        })?;
    let mut items = Vec::new();
    for part in inner.split(',') {
        let part = part.trim();
        if part.is_empty() {
            continue;
        }
        items.push(parse_string(part, line)?);
    }
    Ok(items)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn allow_local_grants_admin_without_credentials() {
        let config = AuthConfig::allow_local();
        assert_eq!(
            config.authenticate(None, None),
            Some(vec![Permission::Admin]),
            "no credential needed"
        );
        assert_eq!(config.granted_permissions(), &[Permission::Admin]);
        assert_eq!(config.challenge_for_session(), None);
    }

    #[test]
    fn token_auth_accepts_only_the_configured_token() {
        let config = AuthConfig::token("s3cret", vec![Permission::Read]);
        assert_eq!(config.challenge_for_session(), None);
        assert_eq!(config.authenticate(None, None), None);
        assert_eq!(
            config.authenticate(
                Some(&AuthResponse::Token {
                    token: "wrong".into()
                }),
                None
            ),
            None
        );
        assert_eq!(
            config.authenticate(
                Some(&AuthResponse::Challenge {
                    response: "x".into()
                }),
                None
            ),
            None
        );
        assert_eq!(
            config.authenticate(
                Some(&AuthResponse::Token {
                    token: "s3cret".into()
                }),
                None
            ),
            Some(vec![Permission::Read])
        );
    }

    #[test]
    fn challenge_response_matches_the_obs_websocket_construction() {
        // Known vector (password "supersecretpassword" with the documented
        // obs-websocket example salt/challenge), computed independently of
        // this crate.
        let challenge = AuthChallenge {
            salt: "lM1GncleQOaCu9lT1yeUZhFYnqhsLLP1G5lAGo3ixaI=".into(),
            challenge: "ztTBnnuqrqaKDzRM3xcVdbYm38ZX7L8CMv0cRAKGYFg=".into(),
        };
        assert_eq!(
            challenge_response("supersecretpassword", &challenge),
            "ScJezpEqvLaUbYm7fZOAYGVa+hwkSJeMSkPA/s7nTtE="
        );
    }

    #[test]
    fn password_config_has_stable_salt_and_fresh_challenges() {
        let config = AuthConfig::password("hunter2", vec![Permission::Admin]);
        let first = config.challenge_for_session().expect("challenge");
        let second = config.challenge_for_session().expect("challenge");
        assert_eq!(first.salt, second.salt, "salt is stable per server start");
        assert_ne!(
            first.challenge, second.challenge,
            "challenge differs per session"
        );
        // 32 raw bytes → 44 base64 chars with padding.
        assert_eq!(first.salt.len(), 44);
        assert_eq!(first.challenge.len(), 44);
        assert_eq!(config.granted_permissions(), &[Permission::Admin]);
    }

    #[test]
    fn password_auth_verifies_against_the_issued_challenge() {
        let config = AuthConfig::password("hunter2", vec![Permission::Read]);
        let challenge = config.challenge_for_session().expect("challenge");
        let answer = |password: &str, challenge: &AuthChallenge| AuthResponse::Challenge {
            response: challenge_response(password, challenge),
        };
        assert_eq!(
            config.authenticate(Some(&answer("hunter2", &challenge)), Some(&challenge)),
            Some(vec![Permission::Read])
        );
        assert_eq!(
            config.authenticate(Some(&answer("wrong", &challenge)), Some(&challenge)),
            None,
            "wrong password"
        );
        assert_eq!(
            config.authenticate(None, Some(&challenge)),
            None,
            "missing response"
        );
        assert_eq!(
            config.authenticate(
                Some(&AuthResponse::Token {
                    token: "hunter2".into()
                }),
                Some(&challenge)
            ),
            None,
            "token method against a password policy"
        );
        // An answer computed for one session's challenge must not
        // authenticate another session (challenge is single-use).
        let other = config.challenge_for_session().expect("challenge");
        assert_eq!(
            config.authenticate(Some(&answer("hunter2", &challenge)), Some(&other)),
            None,
            "response bound to a different session's challenge"
        );
        // No challenge issued → no challenge answer can authenticate.
        assert_eq!(
            config.authenticate(Some(&answer("hunter2", &challenge)), None),
            None
        );
    }

    #[test]
    fn credentials_never_appear_in_debug_output() {
        let token = format!("{:?}", AuthConfig::token("s3cret", vec![]));
        let password = format!("{:?}", AuthConfig::password("hunter2", vec![]));
        assert!(!token.contains("s3cret"));
        assert!(!password.contains("hunter2"));
    }

    #[test]
    fn parses_token_and_permissions() {
        let config = parse_remote_toml(
            r#"
            # Prismcast remote auth
            [remote]
            token = "abc#def" # trailing comment
            permissions = ["read", "control_scenes"]
            "#,
        )
        .expect("parse");
        assert_eq!(
            config,
            AuthConfig::Token {
                token: "abc#def".into(),
                permissions: vec![Permission::Read, Permission::ControlScenes],
            }
        );
    }

    #[test]
    fn parses_password_and_permissions() {
        let config =
            parse_remote_toml("password = \"hunter2\"\npermissions = [\"read\"]\n").expect("parse");
        let AuthConfig::Password {
            password,
            permissions,
            ..
        } = &config
        else {
            panic!("expected password config, got {config:?}");
        };
        assert_eq!(password, "hunter2");
        assert_eq!(permissions, &vec![Permission::Read]);
        // The parsed config is functional: it offers challenges and verifies
        // the matching response.
        let challenge = config.challenge_for_session().expect("challenge");
        assert_eq!(
            config.authenticate(
                Some(&AuthResponse::Challenge {
                    response: challenge_response("hunter2", &challenge)
                }),
                Some(&challenge)
            ),
            Some(vec![Permission::Read])
        );
    }

    #[test]
    fn token_and_password_together_are_a_parse_error() {
        assert!(matches!(
            parse_remote_toml("token = \"a\"\npassword = \"b\"\n"),
            Err(AuthError::Parse { line: 2, .. })
        ));
        assert!(matches!(
            parse_remote_toml("password = \"b\"\ntoken = \"a\"\n"),
            Err(AuthError::Parse { line: 2, .. })
        ));
    }

    #[test]
    fn file_without_token_means_allow_local() {
        let config = parse_remote_toml("permissions = [\"read\"]\n").expect("parse");
        assert_eq!(
            config,
            AuthConfig::AllowLocal {
                permissions: vec![Permission::Read],
            }
        );
        assert_eq!(
            parse_remote_toml("").expect("parse"),
            AuthConfig::allow_local()
        );
    }

    #[test]
    fn malformed_lines_and_unknown_permissions_are_errors() {
        assert!(matches!(
            parse_remote_toml("not a key value"),
            Err(AuthError::Parse { line: 1, .. })
        ));
        assert!(matches!(
            parse_remote_toml("token = abc"),
            Err(AuthError::Parse { .. })
        ));
        assert!(matches!(
            parse_remote_toml("permissions = [\"bogus\"]"),
            Err(AuthError::UnknownPermission(_))
        ));
    }
}
